namespace CurrencyExchangeBot.Models
{
    public class CurrenciesNames
    {
        public CurrencyName AED { get; set; }
        public CurrencyName AFN { get; set; }
        public CurrencyName ALL { get; set; }
        public CurrencyName AMD { get; set; }
        public CurrencyName ANG { get; set; }
        public CurrencyName AOA { get; set; }
        public CurrencyName ARS { get; set; }
        public CurrencyName AUD { get; set; }
        public CurrencyName AWG { get; set; }
        public CurrencyName AZN { get; set; }
        public CurrencyName BAM { get; set; }
        public CurrencyName BBD { get; set; }
        public CurrencyName BDT { get; set; }
        public CurrencyName BGN { get; set; }
        public CurrencyName BHD { get; set; }
        public CurrencyName BIF { get; set; }
        public CurrencyName BMD { get; set; }
        public CurrencyName BND { get; set; }
        public CurrencyName BOB { get; set; }
        public CurrencyName BRL { get; set; }
        public CurrencyName BSD { get; set; }
        public CurrencyName BTN { get; set; }
        public CurrencyName BWP { get; set; }
        public CurrencyName BYN { get; set; }
        public CurrencyName BZD { get; set; }
        public CurrencyName CAD { get; set; }
        public CurrencyName CDF { get; set; }
        public CurrencyName CHF { get; set; }
        public CurrencyName CLF { get; set; }
        public CurrencyName CLP { get; set; }
        public CurrencyName CNY { get; set; }
        public CurrencyName COP { get; set; }
        public CurrencyName CRC { get; set; }
        public CurrencyName CUC { get; set; }
        public CurrencyName CUP { get; set; }
        public CurrencyName CVE { get; set; }
        public CurrencyName CZK { get; set; }
        public CurrencyName DJF { get; set; }
        public CurrencyName DKK { get; set; }
        public CurrencyName DOP { get; set; }
        public CurrencyName DZD { get; set; }
        public CurrencyName EGP { get; set; }
        public CurrencyName ERN { get; set; }
        public CurrencyName ETB { get; set; }
        public CurrencyName EUR { get; set; }
        public CurrencyName FJD { get; set; }
        public CurrencyName FKP { get; set; }
        public CurrencyName GBP { get; set; }
        public CurrencyName GEL { get; set; }
        public CurrencyName GHS { get; set; }
        public CurrencyName GIP { get; set; }
        public CurrencyName GMD { get; set; }
        public CurrencyName GNF { get; set; }
        public CurrencyName GTQ { get; set; }
        public CurrencyName GYD { get; set; }
        public CurrencyName HKD { get; set; }
        public CurrencyName HNL { get; set; }
        public CurrencyName HRK { get; set; }
        public CurrencyName HUF { get; set; }
        public CurrencyName IDR { get; set; }
        public CurrencyName ILS { get; set; }
        public CurrencyName INR { get; set; }
        public CurrencyName IQD { get; set; }
        public CurrencyName IRR { get; set; }
        public CurrencyName ISK { get; set; }
        public CurrencyName JMD { get; set; }
        public CurrencyName JOD { get; set; }
        public CurrencyName JPY { get; set; }
        public CurrencyName KES { get; set; }
        public CurrencyName KGS { get; set; }
        public CurrencyName KHR { get; set; }
        public CurrencyName KMF { get; set; }
        public CurrencyName KPW { get; set; }
        public CurrencyName KRW { get; set; }
        public CurrencyName KWD { get; set; }
        public CurrencyName KZT { get; set; }
        public CurrencyName LAK { get; set; }
        public CurrencyName LBP { get; set; }
        public CurrencyName LKR { get; set; }
        public CurrencyName LRD { get; set; }
        public CurrencyName LSL { get; set; }
        public CurrencyName LYD { get; set; }
        public CurrencyName MAD { get; set; }
        public CurrencyName MDL { get; set; }
        public CurrencyName MGA { get; set; }
        public CurrencyName MKD { get; set; }
        public CurrencyName MMK { get; set; }
        public CurrencyName MNT { get; set; }
        public CurrencyName MOP { get; set; }
        public CurrencyName MRU { get; set; }
        public CurrencyName MUR { get; set; }
        public CurrencyName MVR { get; set; }
        public CurrencyName MWK { get; set; }
        public CurrencyName MXN { get; set; }
        public CurrencyName MXV { get; set; }
        public CurrencyName MYR { get; set; }
        public CurrencyName MZN { get; set; }
        public CurrencyName NAD { get; set; }
        public CurrencyName NGN { get; set; }
        public CurrencyName NIO { get; set; }
        public CurrencyName NOK { get; set; }
        public CurrencyName NPR { get; set; }
        public CurrencyName NZD { get; set; }
        public CurrencyName OMR { get; set; }
        public CurrencyName PAB { get; set; }
        public CurrencyName PEN { get; set; }
        public CurrencyName PGK { get; set; }
        public CurrencyName PHP { get; set; }
        public CurrencyName PKR { get; set; }
        public CurrencyName PLN { get; set; }
        public CurrencyName PYG { get; set; }
        public CurrencyName QAR { get; set; }
        public CurrencyName RON { get; set; }
        public CurrencyName RSD { get; set; }
        public CurrencyName RUB { get; set; }
        public CurrencyName RWF { get; set; }
        public CurrencyName SAR { get; set; }
        public CurrencyName SBD { get; set; }
        public CurrencyName SCR { get; set; }
        public CurrencyName SDG { get; set; }
        public CurrencyName SEK { get; set; }
        public CurrencyName SHP { get; set; }
        public CurrencyName SLL { get; set; }
        public CurrencyName SOS { get; set; }
        public CurrencyName SRD { get; set; }
        public CurrencyName STN { get; set; }
        public CurrencyName SVC { get; set; }
        public CurrencyName SYP { get; set; }
        public CurrencyName SZL { get; set; }
        public CurrencyName THB { get; set; }
        public CurrencyName TJS { get; set; }
        public CurrencyName TMT { get; set; }
        public CurrencyName TND { get; set; }
        public CurrencyName TOP { get; set; }
        public CurrencyName TRY { get; set; }
        public CurrencyName TTD { get; set; }
        public CurrencyName TWD { get; set; }
        public CurrencyName TZS { get; set; }
        public CurrencyName UAH { get; set; }
        public CurrencyName UGX { get; set; }
        public CurrencyName USD { get; set; }
        public CurrencyName UYU { get; set; }
        public CurrencyName UZS { get; set; }
        public CurrencyName VES { get; set; }
        public CurrencyName VND { get; set; }
        public CurrencyName VUV { get; set; }
        public CurrencyName WST { get; set; }
        public CurrencyName XAF { get; set; }
        public CurrencyName XAG { get; set; }
        public CurrencyName XAU { get; set; }
        public CurrencyName XCD { get; set; }
        public CurrencyName XDR { get; set; }
        public CurrencyName XOF { get; set; }
        public CurrencyName XPD { get; set; }
        public CurrencyName XPF { get; set; }
        public CurrencyName XPT { get; set; }
        public CurrencyName YER { get; set; }
        public CurrencyName ZAR { get; set; }
        public CurrencyName ZMW { get; set; }
    }
}